export { default as Tabs } from 'components/Tabs/Tabs'
export { default as Text } from 'components/Text'
export { default as Image } from 'components/Image'
export { default as Box } from 'components/Box'
export { default as Switch } from 'components/Switch'
export { default as WaterLevel } from 'components/WaterLevel'
export { default as Button } from 'components/Button'
